export const ACTION_TYPE = {
  CLEAR_FILTER: "CLEAR_FILTER",
  PRICE_RANGE: "PRICE_RANGE",
  CHECKBOX_CATG: "CHECKBOX_CATG",
  RADIO_RATING: "RADIO_RATING",
  SORT_SELECT: "SORT_SELECT",
  SEARCH: "SEARCH",
};

export const FORM_ACTION_TYPE = {
  ADD_ADDRESS: "ADD_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  SHOW_ADDRESS_FORM: "SHOW_ADDRESS_FORM",
  SELECT_ADDRESS_FORM: "SELECT_ADDRESS_FORM",
};
